## Configuracion de Spring
spring:
  application:
    name: usuarios
  datasource:
    url: jdbc:mysql://mysql-parchando-usuarios.ch9cxccnfz7t.us-east-1.rds.amazonaws.com:3306/parchando?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: AdminUsuarios
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: true

##jdbc:mysql://localhost:3306/parchando?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
##root
##admin

## Configuracion de Instancia
server:
  port: ${PORT:8088}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:ms-usuarios}